let quoteBox = document.getElementById("quoteBox");
// const quoteArray = ["heyyy buddy", "hiiiiii sunny", "ohhhh no", "i am dying"];
const quoteArray = [
  "“Just one small positive thought in the morning can change your whole day.” — Dalai Lama",
  "“Opportunities don't happen, you create them.” — Chris Grosser",
  "“Love your family, work super hard, live your passion.” — Gary Vaynerchuk",
  "“It is never too late to be what you might have been.” — George Eliot",
  "“Don't let someone else's opinion of you become your reality” — Les Brown",
  "“If you're not positive energy, you're negative energy.” Mark Cuban",
  "“I am not a product of my circumstances. I am a product of my decisions.” — Stephen R. Covey",
  "“Do the best you can. No one can do more than that.” ―John Wooden",
  "“If you can dream it, you can do it.” ―Walt Disney",
  "“Do what you can, with what you have, where you are.” ―Theodore Roosevelt",
  "“Life can be much broader once you discover one simple fact: Everything around you that you call life was made up by people that were no smarter than you. And you can change it, you can influence it… Once you learn that, you'll never be the same again.” —Steve Jobs",
  "“Life is like riding a bicycle. To keep your balance you must keep moving.” —Albert Einstein",
  "“What you do speaks so loudly that I cannot hear what you say.” —Ralph Waldo Emerson",
  "“I have never let my schooling interfere with my education.” —Mark Twain",
  "“If you can't yet do great things, do small things in a great way.” ―Napoleon Hill",
  "“If you really want to do something, you'll find a way. If you don't, you'll find an excuse.” ―Jim Rohn",
  "“Be sure you put your feet in the right place, then stand firm.” ―Abraham Lincoln",
  "“Live out of your imagination, not your history.” —Stephen Covey",
  "“Do not wait for the perfect time and place to enter, for you are already onstage.” —Unknown",
  "“The greater the difficulty, the more the glory in surmounting it.” ―Epicurus",
  "Courage doesn't always roar. Sometimes courage is a quiet voice at the end of the day saying, “I will try again tomorrow”. —Mary Anne Radmacher",
  "“If the decisions you make about where you invest your blood, sweat, and tears are not consistent with the person you aspire to be, you’ll never become that person.” ―Clayton M. Christensen",
  "“Success is falling nine times and getting up 10.” —Jon Bon Jovi",
  "“Develop success from failures. Discouragement and failures are two of the surest stepping stones to success.” —Dale Carnegie",
  "“Start where you are. Use what you have. Do what you can.” —Arthur Ashe",
  "“Before anything else, preparation is the key to success.” —Alexander Graham Bell",
  "“Ambition is the path to success. Persistence is the vehicle you arrive in.” —Bill Bradley",
  "“If you don’t have any shadows you’re not in the light.” —Lady Gaga",
  "“There are no regrets in life. Just lessons.” —Jennifer Aniston",
  "“Coming together is a beginning; keeping together is progress; working together is success.” —Henry Ford",
  "“If you have knowledge, let others light their candles in it.” —Margaret Fuller",
  "“A person who never made a mistake never tried anything new.” —Albert Einstein",
  "“How dare you settle for less when the world made it so easy for you to be remarkable?” —Seth Godin",
  "“Challenges are what make life interesting and overcoming them is what makes life meaningful.” —Joshua J. Marine",
  "“We cannot solve problems with the kind of thinking we employed when we came up with them.” —Albert Einstein",
  "“It’s always better to shock people and change people’s expectations than to give them exactly what they think you can do.” —Jonah Hill",
  "“And when you want something, all the universe conspires in helping you achieve it.” —Paulo Coelho",
  "“Don’t judge each day by the harvest you reap but by the seeds that you plant.” —Robert Louis Stevenson",
  "“It is better to fail in originality than to succeed in imitation.” —Herman Melville",
  "“Don’t worry about failure, you only have to be right once.” —Drew Houston",
  "“Experience is a hard teacher because she gives the test first, the lesson afterwards.” —Vernon Sanders Law",
  "“Dream big and dare to fail.” —Norman Vaughan",
  "“Be sure you put your feet in the right place, then stand firm.” —Abraham Lincoln",
  "“I’m not going to continue knocking on that old door that doesn’t open for me. I’m going to create my own door and walk through that.” —W.P. Kinsella",
  "“For the great doesn’t happen through impulse alone, and is a succession of little things that are brought together.” —Vincent Van Gogh",
  "“Life is a succession of lessons which must be lived to be understood.” —Ralph Waldo Emerson",
  "“It’s a good place when all you have is hope and not expectations.” —Danny Boyle",
];
const randomQuotes = Math.floor(Math.random() * quoteArray.length - 1);

quoteBox.innerText = quoteArray[randomQuotes];
